CREATE TABLE test_serial (id SERIAL PRIMARY KEY, payload text);
INSERT INTO test_serial (payload) SELECT 'a' RETURNING *;
INSERT INTO test_serial (id, payload) SELECT 2, 'a' RETURNING *;
INSERT INTO test_serial (payload) SELECT 'a' RETURNING *;

CREATE TABLE test_identity ( id INTEGER generated by default as identity PRIMARY KEY, payload text);
INSERT INTO test_identity (payload) SELECT 'a' RETURNING *;
INSERT INTO test_identity (id, payload) SELECT 1, 'a' RETURNING *;
INSERT INTO test_identity (id, payload) SELECT 100000, 'a' RETURNING *;

\ds

CREATE TABLE test_identity2 ( id INTEGER generated always as identity PRIMARY KEY, payload text);
INSERT INTO test_identity2 (id, payload) SELECT 1, 'a' RETURNING *;